config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :admin_users, ActiveAdmin::Devise.config
  #ActiveAdmin.routes(self)
  root 'tasks#index'

  resources :tasks do
    member do
      get :delete
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  has_event :complete

    enum priorities: {Normal: 'Normal', Medium: 'Medium', High: 'High'}

    validates_presence_of :title
    validates_length_of :title, :maximum => 40
    validates_length_of :description, :maximum => 1024

    scope :recent_tasks, ->(since_last_n_days: 3) {
        where('created_at > ?', DateTime.current - since_last_n_days.days )
    }

    scope :is_completed, -> {
        where(completed: true)
    }

    scope :is_incompleted, -> {
        where(completed: false)
    }

    scope :priority_normal, -> {
        where(priority: "Normal")
    }

    scope :priority_medium, -> {
        where(priority: "Medium")
    }

    scope :priority_high, -> {
        where(priority: "High")
    }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.order(completed: :ASC, priority: :ASC)
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new(:completed => false , :priority => 'Normal')
  end

  def create
    @task = Task.new(task_params)
    if task_params[:completed] == "true"
      @task[:completiontime] = Time.now
      @task.save
    end

    if @task.save
      flash[:notice] = "Task created successfully."
      redirect_to(tasks_path)
    else
      flash[:error] = "Title cannot be empty and should not exceed 40 characters"
      render('new')
    end
  end

  def edit
    @task = Task.find(params[:id]) 
  end

  def update
    @task = Task.find(params[:id])

    if @task.completed == false && task_params[:completed] == "true"
      @task[:completiontime] = Time.now
      @task.save
    end

    if @task.update(task_params)
      flash[:notice] = "Task updated successfully."
      redirect_to(task_path(@task))
    else
      flash[:error] = "Title cannot be empty and should not exceed 40 characters"
      render('edit')
    end
  end

  def delete
    @task = Task.find(params[:id])
  end
 
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "Task '#{@task.title}' destroyed successfully."
    redirect_to(tasks_path)
  end

  private

    def task_params
      params.require(:task).permit(:title, :description , :priority, :completed)
    end
      
end

app/helpers/application_helper.rb
module ApplicationHelper
    def error_messages_for(object)
        render(:partial => 'application/error_messages', :locals => {:object => object})
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="error-explanation">
    <h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Task form fields">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Description</th>
        <td><%= f.text_area(:description) %></td>
      </tr>
      <tr>
        <th>Priority</th>
        <td><%= f.select :priority, Task.priorities.keys %></td>
      </tr>
      <tr>
        <th>Status</th>
        <td><%= f.radio_button :completed, true %> Completed 
        <%= f.radio_button :completed, false %> Pending</td>
      </tr>
      </table>
      <br> </br>

app/views/tasks/delete.html.erb
<%= link_to("<< Back to List", tasks_path, :class => 'back-link') %>

<div class="tasks-delete">
  <h2>Delete Task</h2>

  <%= form_for(@task, :method => 'delete') do |f| %>

    <h3>Are you sure you want to delete?</h3>
    <h3><%= @task.title %></h3>

    <div class="form-buttons">
      <h3><%= f.submit("Delete Task") %></h3>
    </div>

  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= link_to("<< Back to List", tasks_path, :class => 'back-link') %>

<div class="tasks edit">
  <h2>Update Task</h2>

  <%= form_for(@task) do |f| %>

      <%= render(:partial => 'form', :locals => {:f => f}) %>
      
    <div class="form-buttons">
      <%= f.submit("Update Task") %>
    </div>

  <% end %>

</div>

app/views/tasks/index.html.erb
<div class="tasks index">

  <div class="h1anchor">
  <h1>Welcome To Your ToDo List</h1> 

  <h3><%= button_to("+  Add New Task", new_task_path, :method => :get , :class => 'form-buttons') %></h3>

  </div>
  
  <br> </br>
  
  <table class="listing" summary="Task list">
    <tr class="header">
      <th>Tasks</th>
      <th>Priority</th>
      <th>Status</th>
      <th colspan="3"> Actions </th>
    </tr>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td class="center"><%= task.priority %></td>
      <td class="center"><%= task.completed ? 'Completed' : 'Pending' %></td>
      <td><%= link_to "Show", task_path(task) %></td>
      <td><%= link_to "Edit", edit_task_path(task) %></td>
      <td><%= link_to "Delete", delete_task_path(task) %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/tasks/new.html.erb
<%= link_to("<< Back to List", tasks_path, :class => 'back-link') %>

<div class="tasks new">
  <h2>Create Task</h2>
  <%= form_for(@task, :url => tasks_path, :method => 'post') do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>
    </table>
    <br> </br>

    <div class="form-buttons">
      <h3><%= f.submit("Create Task") %></h3>
    </div>

  <% end %>
</div>

app/views/tasks/show.html.erb
<%= link_to("<< Back to List", tasks_path, :class => 'back-link') %>

<div class="tasks show">
  <h2>Show Task</h2>

  <table summary="Task detail view">
      <th>Title</th>
      <td><%= @task.title %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @task.description %></td>
    </tr>
    <tr>
      <th>Priority</th>
      <td><%= @task.priority %></td>
    </tr>
    <tr>
      <th>Status</th>
      <td><%= @task.completed ? 'Completed' : 'Pending' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @task.created_at.strftime("%d-%b-%y %A %H:%M") %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @task.updated_at.strftime("%d-%b-%y %A %H:%M") %></td>
    </tr>
    <% if @task.completed %>
      <tr>
        <th>Completion Time</th>
        <% if @task.completiontime != nil %>
          <td><%= @task.completiontime.strftime("%d-%b-%y %A %H:%M") %></td>
        <% else %>
          <td><%= @task.created_at.strftime("%d-%b-%y %A %H:%M") %></td>
        <% end %>
      </tr>
    <%end%>
  </table>

</div>